name: Run Python script

on:
    push:
    workflow_dispatch:
    schedule:
        - cron:  '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install pandas requests
    - name: Run script
      run: python status_scraper.py
    - name: Upload output CSV
      uses: actions/upload-artifact@v2
      with:
        name: output-csv
        path: ./uitvoer_*.csv
