name: Run Python script

on:
    push:
    workflow_dispatch:
    schedule:
    # Draait elke dag om middernacht
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install pandas requests

    - name: Run script
      run: python status_scraper.py

    - name: List files in current directory
      run: ls -l
