on:
    push:
    workflow_dispatch:
    schedule:
        - cron:  '*/10 * * * *'

permissions: write-all

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v3
            - run: status_scraper.py
            - run: |-
                  git config user.name 'GitHub Actions'
                  git config user.email 'actions@users.noreply.github.com'
                  git add -A
                  git commit -m 'Updates' || exit 0
                  git push
